# 튜토리얼 및 메인 페이지
naver_alert_allow_button = '//android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_button"]'
naver_first_start_button = '//android.widget.TextView[@content-desc="네이버 시작하기 버튼"]'
later_login_button = '//android.widget.TextView[@resource-id="com.nhn.android.search.SearchMain:id/laterLoginBtn"]'
naver_second_start_button = '//android.widget.TextView[@resource-id="com.nhn.android.search.SearchMain:id/locationStartBtn"]'
naver_noti_allow_button = '//android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_foreground_only_button"]'
naver_location_allow_button = '//android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_foreground_only_button"]'
naver_home_button = '//android.view.ViewGroup[@content-desc="홈 버튼"]/android.view.ViewGroup'
naver_tutorial_viewer = '//android.widget.ImageView[@resource-id="com.nhn.android.search.SearchMain:id/dimmedCoachCenterDetail"]'
naver_main_page_viewer = '//android.widget.ImageView[@resource-id="com.nhn.android.search.SearchMain:id/searchBarLogoViewBg"]'
naver_main_search_field = '//android.view.View[@content-desc="검색어 또는 URL 입력, 버튼"]'
naver_main_search_field_detail = '//android.widget.EditText[@content-desc="검색어 또는 URL 입력"]'
naver_search_field_icon = '//android.widget.ImageView[@content-desc="검색"]'
naver_search_result_airline = '(//android.view.View[@text="네이버 항공권"])[1]'

# 네이버 항공권 페이지
naver_airline_page_top_bar = '//android.view.View[@resource-id="__next"]/android.view.View/android.view.View[1]/android.view.View[1]'
naver_airline_roundtrip_tap = '//android.view.View[@text="왕복"]'
naver_airline_oneway_tap = '//android.view.View[@text="편도"]'
naver_airline_departure_menu = '//android.widget.Button[@text="ICN 인천"]'
naver_airline_departure_search_field = '//android.widget.EditText'
naver_airline_departure_place = '//android.view.View[@content-desc="인천, 대한민국Incheon, Korea Republic of ICN인천국제공항Incheon Int Arpt"]'
naver_airline_arrival_menu = '//android.widget.Button[@text="도착 선택"]'
naver_airline_arrival_search_field = '//android.widget.EditText'
naver_airline_arrival_place = '//android.view.View[@content-desc="오사카, 일본Osaka, Japan OSA"]'
naver_airline_setup = '//android.view.View[@resource-id="__next"]/android.view.View/android.view.View[3]/android.view.View/android.view.View/android.view.View[1]'